name: nav_bottom_bar
description: A Simple Bottom Nav Bar for home page with clear and elegant looks. Make your app design cool with this design
version: 0.0.3
homepage: https://github.com/Yaungku/nav_bottom_bar.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.nav_bottom_bar
        pluginClass: NavBottomBarPlugin
      ios:
        pluginClass: NavBottomBarPlugin

